// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmLogin(arg1:string):Promise<string>;

export function Download(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetBookShelf(arg1:string,arg2:string):Promise<string>;

export function GetLoginUid():Promise<string>;

export function Greet(arg1:string):Promise<string>;
