// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmLogin(arg1) {
  return window['go']['main']['App']['ConfirmLogin'](arg1);
}

export function Download(arg1, arg2, arg3) {
  return window['go']['main']['App']['Download'](arg1, arg2, arg3);
}

export function GetBookShelf(arg1, arg2) {
  return window['go']['main']['App']['GetBookShelf'](arg1, arg2);
}

export function GetLoginUid() {
  return window['go']['main']['App']['GetLoginUid']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
